### ISSUE TITLE
How was previous issue fixed on "Cannot use duplicate file names" ?

### ISSUE THREAD

**Issue by envaidya** [dleutnant/swmmr#78]
Hey, I am looking for your little suggestion. How was the previous issue on #58 and #59 resolved? My problem is simulation from EPA 5.1.015 from GUI runs successfully but from run_swmm command it shows the error "_**Cannot use duplicate file name**_", "**_In  normalizePath(path.expand(path), winslash, musk work):...; The system cannot find the file specified_**"

Previous suggestions seems like installing swmmr library from github and not from CRAN. I did exactly the same. I am giving directory to .inp, .out, .rpt all inside "ext data" folder under R4.2.1. Although I only have C: in my laptop, I have full access to the my user account. It do not seem to resolve. Have anyone found work around to this issue? The issue was closed earlier so I wonder what was the right solution. Thanks for your helpful feedback.

**Comment by hsonne** [comment]
Hi, @envaidya, @dleutnant asked me to help him maintain this package. Since the last weeks I worked a lot on the code. I already tried to improve the error reporting. I do all changes on the `dev` branch of this repository. Would you like to install the package from there:
```
remotes::install_github("dleutnant/swmmr@dev")
```
and check the error messages that you receive when you try to reproduce what you were reporting about here?

**Comment by envaidya** [comment]
Thank you very much for your suggestion. It indeed helps.
